import Link from "next/link";
import type { HomeDashboardData } from "@/modules/groups/contracts";
import { JoinedGroupCard } from "./joined-group-card";
import { UpcomingActivityItem } from "./upcoming-activity";
import { RecommendedGroups } from "./recommended-groups";

export function HomeDashboard({ data, userName }: { data: HomeDashboardData; userName: string }) {
  return <main className="app-shell app-shell--animated min-h-[100dvh] bg-[var(--paper)] text-[var(--ink)]"><div className="mx-auto max-w-[1400px] px-5 pb-16 pt-10 sm:px-8 sm:pb-24 lg:px-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[var(--accent-strong)]">Welcome back, {userName}</p><h1 className="font-display mt-3 max-w-[10ch] text-5xl font-black leading-[0.92] tracking-[-0.08em] sm:text-6xl">Ready for your next session?</h1></div><Link className="rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-extrabold text-[var(--accent-foreground)]" href="/discover">Search other groups</Link></div>{data.upcomingActivities.length > 0 && <section aria-labelledby="upcoming-title" className="mt-12 rounded-[1.5rem] border border-[var(--line-strong)] bg-[var(--surface)] px-5 sm:px-7"><div className="flex items-end justify-between gap-4 pt-6"><h2 className="font-display text-2xl font-black tracking-[-0.06em]" id="upcoming-title">Upcoming training & events</h2><span className="text-sm font-bold text-[var(--muted)]">{data.upcomingActivities.length} ahead</span></div><ul className="mt-2">{data.upcomingActivities.slice(0, 5).map((activity) => <UpcomingActivityItem activity={activity} key={activity.id} />)}</ul></section>}{data.joinedGroups.length > 0 ? <section aria-labelledby="joined-title" className="mt-12"><div className="flex items-end justify-between gap-4"><h2 className="font-display text-3xl font-black tracking-[-0.06em]" id="joined-title">Your groups</h2><span className="text-sm font-bold text-[var(--muted)]">{data.joinedGroups.length} joined</span></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{data.joinedGroups.map((group) => <JoinedGroupCard group={group} key={group.membershipId} />)}</div></section> : <section className="mt-12 rounded-[1.5rem] bg-[var(--surface-muted)] px-6 py-10"><h2 className="font-display text-3xl font-black tracking-[-0.06em]">Your groups will live here.</h2><p className="mt-3 max-w-xl leading-7 text-[var(--muted)]">Find a welcoming group, join a session, and make your next plan.</p><Link className="mt-6 inline-flex rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-extrabold text-[var(--accent-foreground)]" href="/discover">Find a group</Link></section>}<div className="mt-14"><RecommendedGroups groups={data.recommendedGroups} /></div></div></main>;
}
